name: Update Last Commit Timestamp

permissions:
  contents: write


on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows you to run manually

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit timestamp
        run: |
          rm -rf *
          LAST_COMMIT_TIME=$(git log -1 --format=%cd --date=iso -- update.sh)
          echo "Last commit timestamp: $LAST_COMMIT_TIME"
          echo "Last Commit: $LAST_COMMIT_TIME" > last_commit.txt

      - name: Push timestamp to separate branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Clone the repo into a temp folder
          git clone --depth=1 --single-branch --branch=time-stamp https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} tmp-repo || \
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} tmp-repo

          cd tmp-repo

          # If branch doesn't exist, create orphan
          git checkout time-stamp || (git checkout --orphan time-stamp && git rm -rf .)

          cp ../last_commit.txt .

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_commit.txt
          git commit -m "Update last commit timestamp" || echo "No changes to commit"
          git push origin time-stamp --force