name: Update Last Commit Timestamp

permissions:
  contents: write


on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows you to run manually

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit timestamp
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%cd --date=iso)
          echo "Last commit timestamp: $LAST_COMMIT_TIME"
          echo "Last Commit: $LAST_COMMIT_TIME" > last_commit.txt

      - name: Commit and push changes
        env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_commit.txt
          git commit -m "Update last commit timestamp" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:time-stamp
        
