name: Update Last Commit Timestamp

permissions:
  contents: write


on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows you to run manually

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit timestamp
        run: |
          rm -rf *
          LAST_COMMIT_TIME=$(git log -1 --format=%cd --date=iso)
          echo "Last commit timestamp: $LAST_COMMIT_TIME"
          echo "Last Commit: $LAST_COMMIT_TIME" > last_commit.txt

      - name: Push timestamp to separate branch
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # clone just the other branch in a temp folder
          git clone --depth=1 --branch=last-commit-timestamp https://x-access-token:${TOKEN}@github.com/${{ github.repository }} timestamp-branch || \
          git clone --depth=1 https://x-access-token:${TOKEN}@github.com/${{ github.repository }} timestamp-branch && \
          cd timestamp-branch && git checkout --orphan last-commit-timestamp && git rm -rf .

          cd timestamp-branch
          echo "Writing timestamp file..."
          cp ../last_commit.txt .

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_commit.txt
          git commit -m "Update last commit timestamp"
          git push origin last-commit-timestamp --force